version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: '/src/main/resources/org/csanchez/jenkins/plugins/kubernetes'
  schedule:
    interval: 'daily'
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
